version: '3.3'

services:
  data:
    image: elasticsearch:7.17.0
    environment:
       discovery.type: single-node
    ports:
      - 9200:9200
    volumes:
      - ./jvm.options:/usr/share/elasticsearch/config/jvm.options

  kibana:
    image: kibana:7.17.0
    environment:
      ELASTICSEARCH_UTL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601